import localFont from "next/font/local";
import { Roboto } from 'next/font/google'
import "./globals.css";
import { SideNav } from "./components/Navbar/SideNav";
import SmoothScrolling from "./lib/SmoothScroll";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased cursor shape`}
      >
        <SideNav />
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
